import createError from "../utils/CreateError"

export const createReview = async (req, res, next) => {
  try {

  } catch(err){
    next(err)
  }
}

export const getReview = async (req, res, next) => {
  try {

  } catch(err){
    next(err)
  }
}

export const deleteReview = async (req, res, next) => {
  try {

  } catch(err){
    next(err)
  }
}
